### ISSUE TITLE
Crash, now I'm wrenched and broke:(

### ISSUE THREAD

**Issue by The96rf** [MobilePorting/FNF-JS-Engine-Mobile#4]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

It crashes anytime I start

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Error!

Null Object Reference

TitleState.update() (line 332]

flixel/FlxState.tryUpdate() (line 239] flixel/FlxGame.update() (line 749]

flixel/FlxGame.step() [line 679]

flixel/FlxGame.onEnterFrame() (line 552]

openfl/events/EventDispatcher_dispatchEvent() [line 426]

openfl/display/DisplayObject_dispatch() (line 1398]
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by mcagabe19** [comment]
delete assets and mods, fully reinstall

**Comment by The96rf** [comment]
Nope, didn't work

**Comment by The96rf** [comment]
> delete assets and mods, fully reinstall and update

Freaking files "piracy" update now I can't delete it

**Comment by mcagabe19** [comment]
> Nope, didn't work

can you try actions build

**Comment by mcagabe19** [comment]
probably fixed but will be on next release
