### ISSUE TITLE
Idk how to

### ISSUE THREAD

**Issue by einbuis07** [MobilePorting/FNF-JS-Engine-Mobile#8]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

How to open chart editor in mobile

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

**Comment by moxie-coder** [comment]
there's an button to open it, but I don't remember which one

**Comment by mcagabe19** [comment]
and on pause screen

**Comment by einbuis07** [comment]
Bruh I seen I pause screen I didn't get the chart editor button

**Comment by mcagabe19** [comment]
update ur js engine to latest then

**Comment by einbuis07** [comment]
ok?
