### ISSUE TITLE
it Gives error everytime i download

### ISSUE THREAD

**Issue by Gamermertcan** [MobilePorting/FNF-JS-Engine-Mobile#9]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

i cant download because it Gives this error everytime: (Requires authorization)(android 12)
How do i even give Authority?
![Screenshot_20240914-162939](https://github.com/user-attachments/assets/635c42df-3d59-41f4-a585-9f38961fdccc)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did'nt even download

**Comment by mcagabe19** [comment]
bad internet, use download managers like adm or cry about it

**Comment by Gamermertcan** [comment]
> bad internet, use download managers like adm or cry about it

my internet is good, its not About internet, it says "Requires authorization"
